apiVersion: v1
kind: Service
metadata:
  name: blogcss-service
spec:
  selector:
    app: blogcss
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080 
  type: NodePort

